language: erlang

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master

before_install:
  - sudo apt-get install luajit luarocks

install:
  - sudo luarocks install luafilesystem 1.6.2
  - sudo luarocks install busted 1.11.1
  - sudo luarocks install luasocket

services:
  - cassandra

script: "busted"

notifications:
  recipients:
    - jbochi@gmail.com
  email:
    on_success: change
    on_failure: always
